FROM php:8.3-apache

RUN docker-php-ext-install pdo_mysql

COPY docker/php-test.ini /usr/local/etc/php/conf.d/jdev-test.ini

RUN a2enmod rewrite \
    && echo 'ServerName localhost' > /etc/apache2/conf-available/servername.conf \
    && a2enconf servername \
    && sed -ri 's!/var/www/html!/var/www/html/public!g' \
        /etc/apache2/sites-available/*.conf \
        /etc/apache2/apache2.conf \
        /etc/apache2/conf-available/*.conf

WORKDIR /var/www/html
